/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
    mesh_0_3: THREE.Mesh;
    mesh_0_4: THREE.Mesh;
    mesh_0_5: THREE.Mesh;
    mesh_0_6: THREE.Mesh;
    mesh_0_7: THREE.Mesh;
    mesh_0_8: THREE.Mesh;
    mesh_0_9: THREE.Mesh;
    mesh_0_10: THREE.Mesh;
    mesh_0_11: THREE.Mesh;
    mesh_0_12: THREE.Mesh;
    mesh_0_13: THREE.Mesh;
    mesh_0_14: THREE.Mesh;
    mesh_1: THREE.Mesh;
    mesh_1_1: THREE.Mesh;
    mesh_1_2: THREE.Mesh;
    mesh_1_3: THREE.Mesh;
    mesh_1_4: THREE.Mesh;
    mesh_1_5: THREE.Mesh;
    mesh_1_6: THREE.Mesh;
    mesh_1_7: THREE.Mesh;
    mesh_1_8: THREE.Mesh;
    mesh_2: THREE.Mesh;
    mesh_2_1: THREE.Mesh;
    mesh_2_2: THREE.Mesh;
    mesh_2_3: THREE.Mesh;
    mesh_2_4: THREE.Mesh;
    mesh_2_5: THREE.Mesh;
    mesh_2_6: THREE.Mesh;
    mesh_2_7: THREE.Mesh;
    mesh_2_8: THREE.Mesh;
    mesh_2_9: THREE.Mesh;
    mesh_2_10: THREE.Mesh;
    mesh_2_11: THREE.Mesh;
    mesh_2_12: THREE.Mesh;
    mesh_2_13: THREE.Mesh;
    mesh_2_14: THREE.Mesh;
    mesh_3: THREE.Mesh;
    mesh_3_1: THREE.Mesh;
    mesh_3_2: THREE.Mesh;
    mesh_3_3: THREE.Mesh;
    mesh_3_4: THREE.Mesh;
    mesh_3_5: THREE.Mesh;
    mesh_3_6: THREE.Mesh;
    mesh_3_7: THREE.Mesh;
    mesh_3_8: THREE.Mesh;
    mesh_4: THREE.Mesh;
    mesh_4_1: THREE.Mesh;
    mesh_4_2: THREE.Mesh;
    mesh_4_3: THREE.Mesh;
    mesh_4_4: THREE.Mesh;
    mesh_4_5: THREE.Mesh;
    mesh_4_6: THREE.Mesh;
    mesh_4_7: THREE.Mesh;
    mesh_4_8: THREE.Mesh;
    mesh_4_9: THREE.Mesh;
    mesh_4_10: THREE.Mesh;
    mesh_4_11: THREE.Mesh;
    mesh_4_12: THREE.Mesh;
    mesh_4_13: THREE.Mesh;
    mesh_4_14: THREE.Mesh;
    mesh_5: THREE.Mesh;
    mesh_5_1: THREE.Mesh;
    mesh_5_2: THREE.Mesh;
    mesh_5_3: THREE.Mesh;
    mesh_5_4: THREE.Mesh;
    mesh_5_5: THREE.Mesh;
    mesh_5_6: THREE.Mesh;
    mesh_5_7: THREE.Mesh;
    mesh_5_8: THREE.Mesh;
    mesh_6: THREE.Mesh;
    mesh_6_1: THREE.Mesh;
    mesh_6_2: THREE.Mesh;
    mesh_6_3: THREE.Mesh;
    mesh_6_4: THREE.Mesh;
    mesh_6_5: THREE.Mesh;
    mesh_6_6: THREE.Mesh;
    mesh_6_7: THREE.Mesh;
    mesh_6_8: THREE.Mesh;
    mesh_6_9: THREE.Mesh;
    mesh_6_10: THREE.Mesh;
    mesh_6_11: THREE.Mesh;
    mesh_6_12: THREE.Mesh;
    mesh_6_13: THREE.Mesh;
    mesh_6_14: THREE.Mesh;
    mesh_7: THREE.Mesh;
    mesh_7_1: THREE.Mesh;
    mesh_7_2: THREE.Mesh;
    mesh_7_3: THREE.Mesh;
    mesh_7_4: THREE.Mesh;
    mesh_7_5: THREE.Mesh;
    mesh_7_6: THREE.Mesh;
    mesh_7_7: THREE.Mesh;
    mesh_7_8: THREE.Mesh;
    mesh_8: THREE.Mesh;
    mesh_8_1: THREE.Mesh;
    mesh_8_2: THREE.Mesh;
    mesh_8_3: THREE.Mesh;
    mesh_8_4: THREE.Mesh;
    mesh_8_5: THREE.Mesh;
    mesh_8_6: THREE.Mesh;
    mesh_8_7: THREE.Mesh;
    mesh_8_8: THREE.Mesh;
    mesh_8_9: THREE.Mesh;
    mesh_8_10: THREE.Mesh;
    mesh_8_11: THREE.Mesh;
    mesh_8_12: THREE.Mesh;
    mesh_8_13: THREE.Mesh;
    mesh_8_14: THREE.Mesh;
    mesh_9: THREE.Mesh;
    mesh_9_1: THREE.Mesh;
    mesh_9_2: THREE.Mesh;
    mesh_9_3: THREE.Mesh;
    mesh_9_4: THREE.Mesh;
    mesh_9_5: THREE.Mesh;
    mesh_9_6: THREE.Mesh;
    mesh_9_7: THREE.Mesh;
    mesh_9_8: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_10_1: THREE.Mesh;
    mesh_10_2: THREE.Mesh;
    mesh_10_3: THREE.Mesh;
    mesh_10_4: THREE.Mesh;
    mesh_10_5: THREE.Mesh;
    mesh_10_6: THREE.Mesh;
    mesh_10_7: THREE.Mesh;
    mesh_10_8: THREE.Mesh;
    mesh_10_9: THREE.Mesh;
    mesh_10_10: THREE.Mesh;
    mesh_10_11: THREE.Mesh;
    mesh_11: THREE.Mesh;
    mesh_11_1: THREE.Mesh;
    mesh_11_2: THREE.Mesh;
    mesh_11_3: THREE.Mesh;
    mesh_11_4: THREE.Mesh;
    mesh_11_5: THREE.Mesh;
    mesh_11_6: THREE.Mesh;
    mesh_11_7: THREE.Mesh;
    mesh_12: THREE.Mesh;
    mesh_12_1: THREE.Mesh;
    mesh_12_2: THREE.Mesh;
    mesh_12_3: THREE.Mesh;
    mesh_12_4: THREE.Mesh;
    mesh_12_5: THREE.Mesh;
    mesh_12_6: THREE.Mesh;
    mesh_12_7: THREE.Mesh;
    mesh_12_8: THREE.Mesh;
    mesh_12_9: THREE.Mesh;
    mesh_12_10: THREE.Mesh;
    mesh_12_11: THREE.Mesh;
    mesh_12_12: THREE.Mesh;
    mesh_12_13: THREE.Mesh;
    mesh_12_14: THREE.Mesh;
    mesh_12_15: THREE.Mesh;
    mesh_12_16: THREE.Mesh;
    mesh_12_17: THREE.Mesh;
    mesh_12_18: THREE.Mesh;
    mesh_12_19: THREE.Mesh;
    mesh_12_20: THREE.Mesh;
    mesh_12_21: THREE.Mesh;
    mesh_12_22: THREE.Mesh;
    mesh_12_23: THREE.Mesh;
    mesh_12_24: THREE.Mesh;
    mesh_12_25: THREE.Mesh;
    mesh_12_26: THREE.Mesh;
    mesh_12_27: THREE.Mesh;
    mesh_12_28: THREE.Mesh;
    mesh_12_29: THREE.Mesh;
    mesh_12_30: THREE.Mesh;
    mesh_12_31: THREE.Mesh;
    mesh_12_32: THREE.Mesh;
    mesh_12_33: THREE.Mesh;
    mesh_12_34: THREE.Mesh;
    mesh_12_35: THREE.Mesh;
    mesh_12_36: THREE.Mesh;
    mesh_12_37: THREE.Mesh;
    mesh_12_38: THREE.Mesh;
    mesh_12_39: THREE.Mesh;
    mesh_12_40: THREE.Mesh;
    mesh_12_41: THREE.Mesh;
    mesh_12_42: THREE.Mesh;
    mesh_12_43: THREE.Mesh;
    mesh_12_44: THREE.Mesh;
    mesh_12_45: THREE.Mesh;
    mesh_12_46: THREE.Mesh;
    mesh_12_47: THREE.Mesh;
    mesh_12_48: THREE.Mesh;
    mesh_13: THREE.Mesh;
    mesh_13_1: THREE.Mesh;
    mesh_13_2: THREE.Mesh;
    mesh_13_3: THREE.Mesh;
    mesh_13_4: THREE.Mesh;
    mesh_13_5: THREE.Mesh;
    mesh_13_6: THREE.Mesh;
    mesh_13_7: THREE.Mesh;
    mesh_13_8: THREE.Mesh;
    mesh_13_9: THREE.Mesh;
    mesh_13_10: THREE.Mesh;
    mesh_13_11: THREE.Mesh;
    mesh_13_12: THREE.Mesh;
    mesh_13_13: THREE.Mesh;
    mesh_13_14: THREE.Mesh;
    mesh_13_15: THREE.Mesh;
    mesh_13_16: THREE.Mesh;
    mesh_13_17: THREE.Mesh;
    mesh_13_18: THREE.Mesh;
    mesh_13_19: THREE.Mesh;
    mesh_13_20: THREE.Mesh;
    mesh_13_21: THREE.Mesh;
    mesh_13_22: THREE.Mesh;
    mesh_13_23: THREE.Mesh;
    mesh_13_24: THREE.Mesh;
    mesh_13_25: THREE.Mesh;
    mesh_13_26: THREE.Mesh;
    mesh_13_27: THREE.Mesh;
    mesh_13_28: THREE.Mesh;
    mesh_13_29: THREE.Mesh;
    mesh_13_30: THREE.Mesh;
    mesh_13_31: THREE.Mesh;
    mesh_13_32: THREE.Mesh;
    mesh_13_33: THREE.Mesh;
    mesh_13_34: THREE.Mesh;
    mesh_13_35: THREE.Mesh;
    mesh_13_36: THREE.Mesh;
    mesh_13_37: THREE.Mesh;
    mesh_13_38: THREE.Mesh;
    mesh_13_39: THREE.Mesh;
    mesh_13_40: THREE.Mesh;
    mesh_13_41: THREE.Mesh;
    mesh_13_42: THREE.Mesh;
    mesh_13_43: THREE.Mesh;
    mesh_13_44: THREE.Mesh;
    mesh_13_45: THREE.Mesh;
    mesh_13_46: THREE.Mesh;
    mesh_13_47: THREE.Mesh;
    mesh_13_48: THREE.Mesh;
    mesh_13_49: THREE.Mesh;
    mesh_13_50: THREE.Mesh;
    mesh_14: THREE.Mesh;
    mesh_14_1: THREE.Mesh;
    mesh_14_2: THREE.Mesh;
    mesh_14_3: THREE.Mesh;
    mesh_14_4: THREE.Mesh;
    mesh_14_5: THREE.Mesh;
    mesh_14_6: THREE.Mesh;
    mesh_14_7: THREE.Mesh;
    Mesh16_Group18_Group12_Group1_Model: THREE.Mesh;
    Mesh17_Group19_Group12_Group1_Model: THREE.Mesh;
    Mesh18_Group20_Group12_Group1_Model: THREE.Mesh;
    mesh_18: THREE.Mesh;
    mesh_18_1: THREE.Mesh;
    mesh_18_2: THREE.Mesh;
    mesh_18_3: THREE.Mesh;
    mesh_18_4: THREE.Mesh;
    mesh_18_5: THREE.Mesh;
    mesh_18_6: THREE.Mesh;
    mesh_18_7: THREE.Mesh;
    mesh_19: THREE.Mesh;
    mesh_19_1: THREE.Mesh;
    mesh_19_2: THREE.Mesh;
    mesh_19_3: THREE.Mesh;
    mesh_19_4: THREE.Mesh;
    mesh_19_5: THREE.Mesh;
    mesh_19_6: THREE.Mesh;
    mesh_19_7: THREE.Mesh;
    mesh_19_8: THREE.Mesh;
    mesh_19_9: THREE.Mesh;
    mesh_19_10: THREE.Mesh;
    mesh_19_11: THREE.Mesh;
    mesh_19_12: THREE.Mesh;
    mesh_19_13: THREE.Mesh;
    mesh_19_14: THREE.Mesh;
    mesh_19_15: THREE.Mesh;
    mesh_19_16: THREE.Mesh;
    mesh_19_17: THREE.Mesh;
    mesh_19_18: THREE.Mesh;
    mesh_19_19: THREE.Mesh;
    mesh_19_20: THREE.Mesh;
    mesh_19_21: THREE.Mesh;
    mesh_19_22: THREE.Mesh;
    mesh_19_23: THREE.Mesh;
    mesh_19_24: THREE.Mesh;
    mesh_19_25: THREE.Mesh;
    mesh_19_26: THREE.Mesh;
    mesh_19_27: THREE.Mesh;
    mesh_19_28: THREE.Mesh;
    mesh_19_29: THREE.Mesh;
    mesh_19_30: THREE.Mesh;
    mesh_19_31: THREE.Mesh;
    mesh_19_32: THREE.Mesh;
    mesh_19_33: THREE.Mesh;
    mesh_19_34: THREE.Mesh;
    mesh_19_35: THREE.Mesh;
    mesh_19_36: THREE.Mesh;
    mesh_19_37: THREE.Mesh;
    mesh_19_38: THREE.Mesh;
    mesh_19_39: THREE.Mesh;
    mesh_19_40: THREE.Mesh;
    mesh_19_41: THREE.Mesh;
    mesh_19_42: THREE.Mesh;
    mesh_19_43: THREE.Mesh;
    mesh_19_44: THREE.Mesh;
    mesh_19_45: THREE.Mesh;
    mesh_19_46: THREE.Mesh;
    mesh_19_47: THREE.Mesh;
    mesh_19_48: THREE.Mesh;
    mesh_19_49: THREE.Mesh;
    mesh_19_50: THREE.Mesh;
    Mesh21_Group23_Group12_Group1_Model: THREE.Mesh;
    mesh_21: THREE.Mesh;
    mesh_21_1: THREE.Mesh;
    mesh_21_2: THREE.Mesh;
    mesh_21_3: THREE.Mesh;
    mesh_21_4: THREE.Mesh;
    mesh_21_5: THREE.Mesh;
    mesh_21_6: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props) {
  const { nodes, materials } = useGLTF("gltf/ship.gltf") as GLTFResult;

  const flagMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      flatShading: true,
    });
  }, []);

  const woodMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      flatShading: true,
      color: 0x8937963,
    });
  }, []);

  const cannonMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      flatShading: true,
      color: 0x888888,
    });
  }, []);

  useEffect(() => {
    flagMaterial.color.setHex(0xff0000);
  }, []);

  return (
    <group rotation={[Math.PI / 2, Math.PI, 0]}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh16_Group18_Group12_Group1_Model.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh17_Group19_Group12_Group1_Model.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh18_Group20_Group12_Group1_Model.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Mesh21_Group23_Group12_Group1_Model.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_1.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_3.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_5.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_7.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_9.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_10.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_11.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_12.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_13.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_0_14.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_1_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_1.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_3.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_5.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_7.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_9.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_10.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_11.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_12.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_13.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_2_14.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_3_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_1.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_3.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_5.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_7.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_9.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_10.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_11.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_12.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_13.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_4_14.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_5_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_1.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_3.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_5.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_7.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_9.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_10.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_11.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_12.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_13.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_6_14.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_7_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_1.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_2.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_3.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_4.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_5.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_6.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_7.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_8.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_9.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_10.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_11.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_12.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_13.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_8_14.geometry}
        material={cannonMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_9_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_9.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_10.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_10_11.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_2.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_6.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_11_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_9.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_10.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_11.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_12.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_13.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_14.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_15.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_16.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_17.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_18.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_19.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_20.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_21.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_22.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_23.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_24.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_25.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_26.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_27.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_28.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_29.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_30.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_31.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_32.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_33.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_34.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_35.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_36.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_37.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_38.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_39.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_40.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_41.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_42.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_43.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_44.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_45.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_46.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_47.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_12_48.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_9.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_10.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_11.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_12.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_13.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_14.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_15.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_16.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_17.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_18.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_19.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_20.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_21.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_22.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_23.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_24.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_25.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_26.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_27.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_28.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_29.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_30.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_31.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_32.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_33.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_34.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_35.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_36.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_37.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_38.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_39.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_40.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_41.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_42.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_43.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_44.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_45.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_46.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_47.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_48.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_49.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_13_50.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_2.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_6.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_14_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_3.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_5.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_18_7.geometry}
        material={flagMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_6.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_7.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_8.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_9.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_10.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_11.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_12.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_13.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_14.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_15.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_16.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_17.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_18.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_19.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_20.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_21.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_22.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_23.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_24.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_25.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_26.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_27.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_28.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_29.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_30.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_31.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_32.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_33.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_34.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_35.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_36.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_37.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_38.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_39.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_40.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_41.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_42.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_43.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_44.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_45.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_46.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_47.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_48.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_49.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_19_50.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_1.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_2.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_3.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_4.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_5.geometry}
        material={woodMaterial}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.mesh_21_6.geometry}
        material={woodMaterial}
      />
    </group>
  );
}

useGLTF.preload("gltf/ship.gltf");
